In [22]:
# we have an avi file, so we want to show the video

In [23]:
!python -m pip install matplotlib 
!python -m pip install opencv-python
!python -m pip install albumentations --user
!python -m pip install tensorboard --user
!python -m pip install pytorch-ignite --user
!python -m pip install torch
!python -m pip install torchvision

You should consider upgrading via the 'c:\Users\sanji\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\sanji\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\sanji\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\sanji\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


     ------------------------------------- 264.1/264.1 KB 16.9 MB/s eta 0:00:00


You should consider upgrading via the 'c:\Users\sanji\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\sanji\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\Users\sanji\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [24]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from torchvision import transforms
import torch

from semantic_segmentation import models
from semantic_segmentation import load_model
from semantic_segmentation import draw_results




In [58]:
torch.cuda.is_available()

False

In [86]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

model = torch.load('./pretrained/model_segmentation_skin_30.pth', map_location=device)
model = load_model(models['FCNResNet101'], model)
model.to(device).eval()
cap = cv2.VideoCapture('vid.avi')
# take the first frame
ret, frame = cap.read()
# show the first frame
cv2.imshow('frame', frame)
print(frame)
fn_image_transform = transforms.Compose(
        [
            transforms.Lambda(lambda im: im),
            transforms.ToTensor(),
            transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ]
    )

image = fn_image_transform(frame)
with torch.no_grad():
    image = image.to(device).unsqueeze(0)
    results = model(image)['out']
    results = torch.sigmoid(results)
    # we want to show the results using cv2
    results = results.squeeze().cpu().numpy()
    print(results[0])
    # plot the histogram
    results = results > 0.05
    # for each index in the results, we want to get the corresponding pixel in the image if the index is true
    # we want to get the pixel in the image and set it to 0

c:\Users\sanji\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\sanji\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=FCN_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1`. You can also use `weights=FCN_ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/fcn_resnet101_coco-7ecb50ca.pth" to C:\Users\sanji/.cache\torch\hub\checkpoints\fcn_resnet101_coco-7ecb50ca.pth
100.0%


[[[164 162 147]
  [163 161 145]
  [164 162 147]
  ...
  [179 171 154]
  [178 168 156]
  [178 168 156]]

 [[163 161 145]
  [163 161 145]
  [163 161 145]
  ...
  [179 171 154]
  [179 170 157]
  [178 168 156]]

 [[162 158 143]
  [164 160 144]
  [165 161 145]
  ...
  [172 170 155]
  [172 170 155]
  [171 169 154]]

 ...

 [[160 158 145]
  [160 158 145]
  [160 158 145]
  ...
  [172 182 171]
  [174 182 171]
  [172 180 170]]

 [[156 158 146]
  [156 158 146]
  [158 158 146]
  ...
  [172 182 171]
  [174 182 171]
  [172 180 170]]

 [[155 157 145]
  [156 158 146]
  [158 158 146]
  ...
  [173 183 172]
  [174 182 171]
  [174 182 171]]]
[0.00260479 0.00260479 0.00260479 0.00260479 0.00257318 0.00251112
 0.00245055 0.00239143 0.00233374 0.00227744 0.00222249 0.00216887
 0.00215796 0.00218912 0.00222073 0.00225279 0.00228532 0.00231832
 0.00235179 0.00238574 0.00239785 0.00238777 0.00237773 0.00236774
 0.00235779 0.00234788 0.00233801 0.00232818 0.00231502 0.00229859
 0.00228227 0.00226607 0.00224998 0

: 

In [68]:
cap.release()
cv2.destroyAllWindows()

In [65]:
# read the avi file
cap = cv2.VideoCapture('vid.avi')
# show the video
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:
        cv2.imshow('frame',frame)
        if cv2.waitKey(15) & 0xFF == ord('q'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()


KeyboardInterrupt: 

In [84]:
cap = cv2.VideoCapture('vid.avi')
# show the video
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:
        # print(frame)
        b = True
        if (b):
            fn_image_transform = transforms.Compose(
                    [
                        transforms.Lambda(lambda im: im),
                        transforms.ToTensor(),
                        transforms.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
                    ]
                )

            image = fn_image_transform(frame)
            with torch.no_grad():
                image = image.to(device).unsqueeze(0)
                results = model(image)['out']
                results = torch.sigmoid(results)
                # we want to show the results using cv2
                results = results.squeeze().cpu().numpy()
                # print(results[0])
                # plot the histogram
                results = results > 0.001
                for i in range(results.shape[0]):
                    for j in range(results.shape[1]):
                        if (results[i][j]):
                            frame[i][j] = 0
                cv2.imshow('frame', frame)
        
        if cv2.waitKey(15) & 0xFF == ord('q'):
            break  

cap.release()
cv2.destroyAllWindows()